version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: rajendra_assignment3
    container_name: assignment
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./:/usr/src/app